cn11.hpc.itu.dk
W0227 14:22:11.809000 1459864 site-packages/torch/distributed/run.py:792] 
W0227 14:22:11.809000 1459864 site-packages/torch/distributed/run.py:792] *****************************************
W0227 14:22:11.809000 1459864 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0227 14:22:11.809000 1459864 site-packages/torch/distributed/run.py:792] *****************************************
loading modelloading model

load model internalload model internal

loading model
load model internal
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [02:06<04:12, 126.29s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [02:06<04:13, 126.83s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [02:06<04:12, 126.29s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [04:17<02:09, 129.33s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [04:17<02:09, 129.34s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [04:18<02:09, 129.56s/it]W0227 15:25:18.695000 1459864 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1461017 closing signal SIGTERM
W0227 15:25:18.772000 1459864 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1461019 closing signal SIGTERM
E0227 15:25:19.687000 1459864 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -9) local_rank: 1 (pid: 1461018) of binary: /home/ccor/.conda/envs/counter/bin/python
Traceback (most recent call last):
  File "/home/ccor/.conda/envs/counter/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccor/.conda/envs/counter/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
intgrads.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-27_15:25:18
  host      : cn11.hpc.itu.dk
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 1461018)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 1461018
========================================================
slurmstepd: error: Detected 1 oom_kill event in StepId=28186.batch. Some of the step tasks have been OOM Killed.
